### ISSUE TITLE
Sign in check issue

### ISSUE THREAD

**Issue by ayubhassan** [Microsoft/xbox-live-unity-plugin#126]
Ok I get null reference exception when I use xboxlive.issigned. Is there any other way to check whether user is signed in?

**Comment by Piecrustius** [comment]
I have used: XboxLiveUserManager.Instance.AvailableXboxLiveUsers[i].User.IsSignedIn when I have multiple users were 'i' is the one I am checking. 

I imagine that if you have only one user that you can check XboxLiveUser.User.IsSignedIn from the UserProfile prefab.

Regardless, I would check if both XboxLiveUser != null and XboxLiveUser.User != null before checking the IsSignedIn member of User.  The UserProfile script seems to do so and, since I think some of the values are set in separate threads, you may not know when it has been set.  I haven't have problems when checking this way.

If you sign out the user while the game is running, at least with multiple users, I think the User member may become null.  Don't quote me on that though :).

**Comment by ayubhassan** [comment]
xboxliveuser != null always returns null!

**Comment by Piecrustius** [comment]
How are you trying to access it?  Is it through the UserProfile prefab/script?  What do you have in your current scene?

**Comment by ayubhassan** [comment]
here is what I got on my script.

`public Class UIManager, Monbehaviour;
{
public XboxLiveUser User;

public void Check(){
if (User.IsSignedIn)
{"blah blah" }}
}`

**Comment by Piecrustius** [comment]
I am doing a similar thing with my own script and not using the UserProfile.cs script.   However, I used it as a starting point to see how they did it.

Take a look at how it is done in UserProfile.cs.  There is a bunch of initialization that occurs before you can access the associated XboxLiveUser.  There is some general initialization in the Awake and Start functions.  The Update function seems to have a two-step process of initializing an XboxLiveUser, including initializing the actual XboxLiveUser variable in the UserProfile class and starting the signin process. 

Maybe the easiest solution for you would be to add a UserProfile prefab to your scene. You may need to add some other prefabs, such as the XboxLiveUser prefab and the XboxLiveServices prefab to your scene. to make it work or get rid of some debug messages about adding them.

Once you add the UserProfile prefab, then your UIManager can get a reference to it.  You should then be able to access the xbox user through that.  You may still need to check if it is initialized, but it would at least provide a path to have a user sign in so that when you get to your "if (User.IsSignedIn{"blah blah" }" section, that User variable will be valid.

**Comment by MSFT-Heba** [comment]
Hi ayubhassan,
We do recommend checking out the UserProfile.cs script for the initializations that need to happen for XboxLiveUser. Without that initialization, the User will remain null resulting in exceptions.

Do let us know how this worked out for you and if you need any more help.
