### ISSUE TITLE
Xbox Live Association Wizard problem

### ISSUE THREAD

**Issue by phime** [Microsoft/xbox-live-unity-plugin#245]
Hello!
I'm trying to make a configuration file for my UWP Xbox live enabled game. When I run Xbox Live Association Wizard problem my game shows in list and after that I get the communication problem.
![error](https://user-images.githubusercontent.com/2223631/43072522-a17995ce-8e76-11e8-92c7-f2078e0e578f.jpg)
Using Unity 2018.2, latest unity-xboxlive-plugin, latest VS 2017 etc.

Cheers!
Dusko Pejacki

**Comment by MSFT-Heba** [comment]
Hi Dusko,
We were able to repro this problem on our end and are actively working on the fix that should be released within the next two days.

Thank you for reporting it!

**Comment by phime** [comment]
Thanks Heba, and if it helps I'm also member of ID@XBOX and Creators program at the same time on this account.

**Comment by phime** [comment]
@MSFT-Heba Tried the new commited Associtation Wizard and it works now ;) Good job!

**Comment by Haddicus** [comment]
If anyone else is having this issue, you have to download the full build and do a compile yourself - the publicly accessible drop in component still contains this issue

**Comment by MSFT-Heba** [comment]
Thanks @phime :) We were testing it on our side, too, to verify. Always awesome to hear back from the community though as we make progress

@Haddicus can you give the latest release a try? Should have this issue fixed.

**Comment by MSFT-Heba** [comment]
We haven't heard back about this issue. We hope that fix did solve it for everyone. 
We're closing this issue now but please feel free to reopen or create a new issue if needed!

**Comment by JamesDeCarlo** [comment]
Do you still need to compile the source or should the unity package in releases be working now? Still having this problem with the latest release being imported to unity.

**Comment by markus2810** [comment]
Still not working!

**Comment by sulemanmuneer4212** [comment]
Hi
I am having kind of same issue. When I try to "Run Xbox Live Association Wizard" it shows me this error.
![Annotation 2020-05-14 143557](https://user-images.githubusercontent.com/65340070/81919566-6f964f00-95f1-11ea-94fe-73958d993ad5.png)

And on partner center dashboard currently it is showing this error.
![Annotation 2020-05-14 144548](https://user-images.githubusercontent.com/65340070/81919967-f2b7a500-95f1-11ea-82f1-cd405b82a8a1.png)

Please help me what could be the possible reasons for these and what could be the possible solutions.

**Comment by ImperialDynamicsOfficial** [comment]
unbelievable but they have STILL not fixed it!!!!!

**Comment by markus2810** [comment]
The easiest way to come around this problem is to add the XboxServices.config file by hand.
Open your unity solution in Visual Studio (by double clicking a script) and add the file to the root of the project. 

![image](https://user-images.githubusercontent.com/2051899/87453214-7c8bea80-c602-11ea-9837-8570317b5aab.png)

Fill out the content of the file carfully. You need to search a bit in the partner center to find all required information.
xeam is our short company name of xeam.games, I did not remove in the company name in the sample, because it is easier to find the correct entries for the fields.

```
{
  "PublisherId": "CN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX",
  "PublisherDisplayName": "xeam",
  "PackageIdentityName": "xeam.<your package name>",
  "DisplayName": "Display Name of your game",
  "AppId": "XXXXXXXXXXXX",
  "ProductFamilyName": "xeam.<your product familyname>",
  "PrimaryServiceConfigId": "00000000-0000-0000-0000-XXXXXXXXXXXX",
  "TitleId": XXXXXXXXXX,
  "Scope" : "xbl.signin xbl.friends",
  "Sandbox": "<Your Sandbox ID>"
}
```

Be careful with the json formatting and line endings.

**Comment by jppresents** [comment]
@markus2810 
Since this seems to still not be fixed (association wizard does not work), I have to create this file by hand as you suggested.

I can not get my login to work on pc and on xbox - (since sandbox id is set on system, on xbox and in the XboxServices.config and Account is added as a Testaccount in Partner-Center) I guess I have an error in my file.

Could you explain where to find "your product familyname" in the partner center?
Can you confirm it is correct, that App Id is the "Store Id" in the partner center?
Can you explain where short company name is configured in partner center?

Thank you in advance!

**Comment by jppresents** [comment]
I got it finally running - my XboxService.config was already ok, thanks to markus2810.

What I was missing was the correct publisher name in the self generated certificate.
For people having the same problem as me:
In VisualStudio double click "Package.appxmanifest", go to the last tab "Packaging", put in the package name from your partner center. Click on "Choose Certificate...", choose "Create...", and as publisher name insert the CN=xxxx Data from the partner center WITHOUT the "CN=" prefix.

After doing this I could finally log in with my xbox account (in dev mode with sandbox) - on pc and xbox one.
