### ISSUE TITLE
Plugins: Failed to load 'Microsoft.Xbox.Services.140.UWP.C' because one or more of its dependencies could not be loaded

### ISSUE THREAD

**Issue by dev-sda1** [microsoft/xbox-live-unity-plugin#279]
When I run the build, no matter what happens it returns with a black screen after the unity splash is displayed. After looking through the log files I found this line:

`Plugins: Failed to load 'Microsoft.Xbox.Services.140.UWP.C' because one or more of its dependencies could not be loaded.` and i'm wondering if this could be the cause of the issue? Would it mean a reinstall of the plugin to try and solve it?

I'm using NET 4.x on everything so that wouldn't be the problem

**Comment by dzrust** [comment]
This is also happening for me too in my project. I can see the `Microsoft.Xbox.Services.UWP.CSharp` in the libs folder, but when the project is built and deployed to the Xbox system I get two dep errors:

1.  Plugins: Failed to load 'WindowsMRXRSDK' because one or more of its dependencies could not be loaded.
2. Plugins: Failed to load 'Microsoft.Xbox.Services.140.UWP.C' because one or more of its dependencies could not be loaded.

In that order.

**Comment by dev-sda1** [comment]
Fixed by moving all files into a new project file
