### ISSUE TITLE
Unable to login in development with Creators Program - How do I provision a regular MSA for my Development Sandbox?

### ISSUE THREAD

**Issue by mgrogin** [microsoft/xbox-live-unity-plugin#290]
I reviewed the documentation at https://docs.microsoft.com/en-us/gaming/xbox-live/xbox-live-test-accounts#types-of-test-accounts and it says "If you are developing a title with the Creators Program, you may only use Regular MSAs that are provisioned for your Development Sandbox."
How do I provision a regular MSA for my Development Sandbox?

**Comment by CarbonFireStudio** [comment]
I had the same issue and managed to fix it by myself...

There's a bug right now and we can't provision a normal xbox account because we have this error message when going to the following link https://partner.microsoft.com/en-us/xboxconfig/TestAccounts/Creator :

> You are unauthorized to view the content on this page. If you believe you should have access please contact your account administrator and request [Access required for this page]

Until Microsoft fix it, there is a workaround. Simply right click on the "Add Account" button and launch your browser inspector to modify html code as the following :

replace 
`<input type="button" class="btn-primary disabled" id="newCreatorButton" value="Add account">`

by

`<input type="button" class="btn-primary" id="newCreatorButton" value="Add account">`

and the button will unlock and indeed work as expected.

**Comment by mgrogin** [comment]
Thanks @CarbonFireStudio this was very helpful.
I'm still having trouble running the sample scenes in the project.
I was able to login on windows but when I try to login on the XBOX it crashes.
Do you have any tips or an updated sample Unity project for Unity 2019?
Thanks! 

> I had the same issue and managed to fix it by myself...
> 
> There's a bug right now and we can't provision a normal xbox account because we have this error message when going to the following link https://partner.microsoft.com/en-us/xboxconfig/TestAccounts/Creator :
> 
> > You are unauthorized to view the content on this page. If you believe you should have access please contact your account administrator and request [Access required for this page]
> 
> Until Microsoft fix it, there is a workaround. Simply right click on the "Add Account" button and launch your browser inspector to modify html code as the following :
> 
> replace
> `<input type="button" class="btn-primary disabled" id="newCreatorButton" value="Add account">`
> 
> by
> 
> `<input type="button" class="btn-primary" id="newCreatorButton" value="Add account">`
> 
> and the button will unlock and indeed work as expected.

**Comment by CarbonFireStudio** [comment]
What is the crash lot saying ?
