### ISSUE TITLE
Missing winmd File

### ISSUE THREAD

**Issue by Seiryu32** [Microsoft/xbox-live-unity-plugin#79]
I downloaded the package and when I tried to build it returned the error:
Assets/Xbox Live/Scripts/Leaderboard.cs: error CS0234 and similar for all components.  I asked on the Unity forum and the package appears to missing the Microsoft.Xbox.Services.winmd file. I did a search for it in my Project Hierarchy and it is indeed missing.

**Comment by MSFT-Heba** [comment]
Hi Seriyu32, 
This unity plugin doesn't use the winmd. 
Would you mind sharing a few more details?

Are you getting the unitypackage from releases of this repo: https://github.com/Microsoft/xbox-live-unity-plugin/releases? Or are you getting the repo and building the package directly?

**Comment by Seiryu32** [comment]
I imported the Xbox.unitypackage directly. Unity doesn't appear to be detecting the plugin correctly. It won't build my app with it. It'll build fine without it so it can't be a bug in my game files. I deleted and re-imported the package several times but got the same errors.  Did I not download the plugin correctly?

**Comment by MSFT-Heba** [comment]
A couple things that could help:
- When you imported the unitypackage, were you following: https://developer.microsoft.com/en-us/games/xbox/docs/xboxlive/xbox-live/get-started-with-creators/configure-xbox-live-in-unity? 
- What is the Windows SDK version being used? A quick way to check that would be looking at the options listed under: Unity Build Settings > (Make sure you've switched platform to Windows Store) > UWP SDK. All installed Windows SDK version will be listed there.
- What scripting backend are you using in Unity? .NET 2.0 or IL2CPP? This can be found under Unity Build Settings > Player Settings > Other Settings > Scripting Backend.

**Comment by Seiryu32** [comment]
Yeah I followed the link directly from: https://developer.microsoft.com/en-us/games/xbox/docs/xboxlive/xbox-live/get-started-with-creators/configure-xbox-live-in-unity
I have Visual Studio 2017 which should have installed the most recent version of the Windows SDK which should be 10.0.15063.0.  I was using .net 2.0, though I tried changing to Subset 2.0 and 4.6. Haven't been able to get it to build with IL2CPP.

**Comment by MSFT-Heba** [comment]
When using the .net 2.0 backend, looking at the errors listed, are they all the same? Are there any other errors? Or are they all: The type or namespace 'Xbox' does not exist in the namespace 'Microsoft'. Are you missing an assembly .... ?

**Comment by Seiryu32** [comment]
Yeah it hits every component.  What I missing in my setup? I must be skipping something.

**Comment by MSFT-Heba** [comment]
When you import the plugin, one of the folders in there is called 'Libs' which actually includes all the libraries that are needed for the plugin including the Microsoft.Xbox namespace. If for any reason these libs are missing, moved or failing, the exact behavior you're describing happens. They should be in the plugin though, which is why it's weird to see you hit this issue.

Something is causing these libraries to fail to import/build for you. 

Let's try a few things here:
- When you import the plugin, do you see the Libs folder and its contents? After importing, are they all still there?
- When you create a new project and import the plugin in there, do you see the same errors?
- When installing Unity, the checkbox for Windows Store .NET scripting backend was selected?
- In your VS installation, are the Universal Windows Apps tools installed?

**Comment by MSFT-Heba** [comment]
The two libraries in the Libs folder that are especially important to look for are:
Assets > Xbox Live > Libs > Unity > Microsoft.Xbox.Services.UnityEditor.CSharp
Assets > Xbox Live > Libs > UWP > Microsoft.Xbox.Services.UWP.CSharp

**Comment by jasonsandlin** [comment]
Please re-open this issue if your still stuck
